version = 1
exclude_patterns = [
  "docs/docs/javascripts/**",
  "docs/ci/**",
  "InvenTree/InvenTree/static/**",
  "ci/**",
  "InvenTree/**/migrations/*.py"
]
test_patterns = [
  "test_.*.py",
  "test.py",
  "tests.py"
]


[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"
