name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@a2d75a8d58b117b19777a910e284ccb082aaf117
        with:
          token: ${{ secrets.INVENTREE_SPONSORS_TOKEN }}
          file: 'README.md'
          organization: true

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc
        with:
          branch: master
          folder: '.'
